name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: aphine-latest

    steps:
    - uses: actions/checkout
    - name: Build the Docker image
      run: docker build --no-cache -t k4rian/citra-room .
